CREATE TABLE role (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  label VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE user (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  pseudo VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role_id INT UNSIGNED NOT NULL,
  FOREIGN KEY(role_id) REFERENCES role(id)
);

CREATE TABLE priority (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  label VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE thing (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  content VARCHAR(255) NOT NULL,
  priority_id INT UNSIGNED NOT NULL,
  FOREIGN KEY(priority_id) REFERENCES priority(id),
  user_id INT UNSIGNED NOT NULL,
  FOREIGN KEY(user_id) REFERENCES user(id)
);